### ISSUE TITLE
upsmon.conf

### ISSUE THREAD

**Issue by xlaguarda** [ntd/ansible-role-nut#5]
The nut role in the upsmon.conf template is always master.
Should not be controlled by nut_role variable?

**Comment by ntd** [comment]
Yes, and also `nut_powervalue` [was defined](https://github.com/ntd/ansible-role-nut/blob/1.1.1/defaults/main.yml#L14) but never used in the templates.

Please, let me know if the recent commints in `dev` fixes your issues, in which case I'll do a quick release ASAP.

**Comment by ntd** [comment]
No news, so I just released 1.2.0 with the above fix included.
